# ===================================================================
# 🌊 LangFlow - Visual AI Workflow Builder (Optional Service)
# ===================================================================

# Note: Using host network mode for better connectivity
# All services can access localhost and external LAN directly

services:
  # LangFlow Visual Workflow Builder
  langflow:
    image: langflowai/langflow:latest
    container_name: automagik-langflow
    restart: unless-stopped
    environment:
      - LANGFLOW_PORT=${LANGFLOW_PORT:-7860}
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_SUPERUSER=${LANGFLOW_SUPERUSER:-automagik}
      - LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD:-automagik_pass}
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY:-your-langflow-secret-key-2024}
      - LANGFLOW_LOG_LEVEL=info
      - LANGFLOW_DATABASE_URL=sqlite:////app/langflow/langflow.db
      - LANGFLOW_CONFIG_DIR=/app/langflow
    volumes:
      - /root/data/langflow:/app/langflow
    network_mode: host
    # Note: Dependencies are managed externally since we're using host network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${LANGFLOW_PORT:-7860}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

