# ===================================================================
# 🐳 Automagik Suite - Core Infrastructure Only (Docker Compose)
# ===================================================================
# This file contains only the core Automagik infrastructure dependencies
# - PostgreSQL databases for am-agents-labs and automagik-spark
# - Redis instances for am-agents-labs and automagik-spark
# Application services run via PM2
# Optional services (Evolution, LangFlow) have separate docker compose files

# Note: Using host network mode for better connectivity
# All services can access localhost and external LAN directly

volumes:
  # PostgreSQL Data
  am-agents-labs-postgres-data:
  automagik-spark-postgres-data: 
  
  # Redis Data
  automagik-spark-redis-data:

services:
  # ================================
  # Infrastructure Services
  # ================================
  
  # PostgreSQL for am-agents-labs (Main Orchestrator)
  am-agents-labs-postgres:
    image: postgres:15-alpine
    container_name: am-agents-labs-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: automagik_agents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5401
    volumes:
      - am-agents-labs-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d automagik_agents -p 5401"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL for automagik-spark (Workflow Engine)
  automagik-spark-postgres:
    image: postgres:15-alpine
    container_name: automagik-spark-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: automagik_spark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5402
    volumes:
      - automagik-spark-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d automagik_spark -p 5402"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for automagik-spark
  automagik-spark-redis:
    image: redis:7-alpine
    container_name: automagik-spark-redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --port 5412 --appendonly yes --requirepass ""
    volumes:
      - automagik-spark-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "5412", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

