# ===================================================================
# 🐳 Automagik Suite - Core Infrastructure Only (Docker Compose)
# ===================================================================
# This file contains only the core Automagik infrastructure dependencies
# - PostgreSQL databases for automagik and automagik-spark
# - Redis instances for automagik and automagik-spark
# Application services run via PM2
# Optional services (Evolution, LangFlow) have separate docker compose files

# Note: Using host network mode for better connectivity
# All services can access localhost and external LAN directly

volumes:
  # PostgreSQL Data
  automagik-postgres-data:
  automagik-spark-postgres-data: 
  
  # Redis Data
  automagik-spark-redis-data:

services:
  # ================================
  # Infrastructure Services
  # ================================
  
  # PostgreSQL for automagik (Main Orchestrator)
  automagik-postgres:
    image: postgres:15-alpine
    container_name: automagik-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: automagik_agents
      POSTGRES_USER: ${POSTGRES_USER:-automagik_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-automagik_pass}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: ${AUTOMAGIK_POSTGRES_PORT:-5401}
    volumes:
      - automagik-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-automagik_user} -d automagik_agents -p ${AUTOMAGIK_POSTGRES_PORT:-5401}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PostgreSQL for automagik-spark (Workflow Engine)
  automagik-spark-postgres:
    image: postgres:15-alpine
    container_name: automagik-spark-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: automagik_spark
      POSTGRES_USER: ${AUTOMAGIK_SPARK_POSTGRES_USER:-spark_user}
      POSTGRES_PASSWORD: ${AUTOMAGIK_SPARK_POSTGRES_PASSWORD:-spark_pass}
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: ${AUTOMAGIK_SPARK_POSTGRES_PORT:-5402}
    volumes:
      - automagik-spark-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTOMAGIK_SPARK_POSTGRES_USER:-spark_user} -d automagik_spark -p ${AUTOMAGIK_SPARK_POSTGRES_PORT:-5402}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for automagik-spark
  automagik-spark-redis:
    image: redis:7-alpine
    container_name: automagik-spark-redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --port ${AUTOMAGIK_SPARK_REDIS_PORT:-5412} --appendonly yes --requirepass "${AUTOMAGIK_SPARK_REDIS_PASSWORD:-spark_redis_pass}"
    volumes:
      - automagik-spark-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${AUTOMAGIK_SPARK_REDIS_PORT:-5412}", "-a", "${AUTOMAGIK_SPARK_REDIS_PASSWORD:-spark_redis_pass}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

